### ISSUE TITLE
Warns in version 1.21.1

### ISSUE THREAD

**Issue by naikyys** [Summiner/ServerPatches#19]
Here is simply the log:

```yml[15:02:03] [Netty Epoll Server IO #1/WARN]: [rs.jamie.serverpatches.libs.retrooper.com.packetevents.PacketEventsAPI] PacketEvents caught an unhandled exception while calling your listener.
java.lang.ArrayIndexOutOfBoundsException: Index 102 out of bounds for length 3
	at ServerPatches-Paper.jar/rs.jamie.serverpatches.libs.retrooper.com.packetevents.wrapper.PacketWrapper.readEnum(PacketWrapper.java:1471) ~[ServerPatches-Paper.jar:?]
	at ServerPatches-Paper.jar/rs.jamie.serverpatches.libs.retrooper.com.packetevents.protocol.component.builtin.item.ItemAttributeModifiers$Modifier.read(ItemAttributeModifiers.java:187) ~[ServerPatches-Paper.jar:?]
	at ServerPatches-Paper.jar/rs.jamie.serverpatches.libs.retrooper.com.packetevents.protocol.component.builtin.item.ItemAttributeModifiers$ModifierEntry.read(ItemAttributeModifiers.java:113) ~[ServerPatches-Paper.jar:?]
	at ServerPatches-Paper.jar/rs.jamie.serverpatches.libs.retrooper.com.packetevents.wrapper.PacketWrapper.readCollection(PacketWrapper.java:1426) ~[ServerPatches-Paper.jar:?]
	at ServerPatches-Paper.jar/rs.jamie.serverpatches.libs.retrooper.com.packetevents.wrapper.PacketWrapper.readList(PacketWrapper.java:1439) ~[ServerPatches-Paper.jar:?]
	at ServerPatches-Paper.jar/rs.jamie.serverpatches.libs.retrooper.com.packetevents.protocol.component.builtin.item.ItemAttributeModifiers.read(ItemAttributeModifiers.java:50) ~[ServerPatches-Paper.jar:?]
	at ServerPatches-Paper.jar/rs.jamie.serverpatches.libs.retrooper.com.packetevents.protocol.component.ComponentTypes$1.read(ComponentTypes.java:88) ~[ServerPatches-Paper.jar:?]
	at ServerPatches-Paper.jar/rs.jamie.serverpatches.libs.retrooper.com.packetevents.wrapper.PacketWrapper.readItemStackModern(PacketWrapper.java:477) ~[ServerPatches-Paper.jar:?]
	at ServerPatches-Paper.jar/rs.jamie.serverpatches.libs.retrooper.com.packetevents.wrapper.PacketWrapper.readItemStack(PacketWrapper.java:496) ~[ServerPatches-Paper.jar:?]
	at ServerPatches-Paper.jar/rs.jamie.serverpatches.libs.retrooper.com.packetevents.wrapper.PacketWrapper.readMap(PacketWrapper.java:427) ~[ServerPatches-Paper.jar:?]
	at ServerPatches-Paper.jar/rs.jamie.serverpatches.libs.retrooper.com.packetevents.wrapper.play.client.WrapperPlayClientClickWindow.read(WrapperPlayClientClickWindow.java:77) ~[ServerPatches-Paper.jar:?]
	at ServerPatches-Paper.jar/rs.jamie.serverpatches.libs.retrooper.com.packetevents.wrapper.PacketWrapper.readEvent(PacketWrapper.java:270) ~[ServerPatches-Paper.jar:?]
	at ServerPatches-Paper.jar/rs.jamie.serverpatches.libs.retrooper.com.packetevents.wrapper.PacketWrapper.<init>(PacketWrapper.java:160) ~[ServerPatches-Paper.jar:?]
	at ServerPatches-Paper.jar/rs.jamie.serverpatches.libs.retrooper.com.packetevents.wrapper.PacketWrapper.<init>(PacketWrapper.java:150) ~[ServerPatches-Paper.jar:?]
	at ServerPatches-Paper.jar/rs.jamie.serverpatches.libs.retrooper.com.packetevents.wrapper.play.client.WrapperPlayClientClickWindow.<init>(WrapperPlayClientClickWindow.java:42) ~[ServerPatches-Paper.jar:?]
	at ServerPatches-Paper.jar/rs.jamie.serverpatches.crashes.listeners.SwapCrashListener.onPacketPlayReceive(SwapCrashListener.java:28) ~[ServerPatches-Paper.jar:?]
	at ServerPatches-Paper.jar/rs.jamie.serverpatches.libs.retrooper.com.packetevents.event.SimplePacketListenerAbstract.onPacketReceive(SimplePacketListenerAbstract.java:49) ~[ServerPatches-Paper.jar:?]
	at ServerPatches-Paper.jar/rs.jamie.serverpatches.libs.retrooper.com.packetevents.event.PacketReceiveEvent.call(PacketReceiveEvent.java:45) ~[ServerPatches-Paper.jar:?]
	at ServerPatches-Paper.jar/rs.jamie.serverpatches.libs.retrooper.com.packetevents.event.EventManager.callEvent(EventManager.java:52) ~[ServerPatches-Paper.jar:?]
	at ServerPatches-Paper.jar/rs.jamie.serverpatches.libs.retrooper.com.packetevents.util.PacketEventsImplHelper.handleServerBoundPacket(PacketEventsImplHelper.java:84) ~[ServerPatches-Paper.jar:?]
	at ServerPatches-Paper.jar/rs.jamie.serverpatches.libs.retrooper.io.packetevents.injector.handlers.PacketEventsDecoder.read(PacketEventsDecoder.java:57) ~[ServerPatches-Paper.jar:?]
	at ServerPatches-Paper.jar/rs.jamie.serverpatches.libs.retrooper.io.packetevents.injector.handlers.PacketEventsDecoder.decode(PacketEventsDecoder.java:64) ~[ServerPatches-Paper.jar:?]
	at ServerPatches-Paper.jar/rs.jamie.serverpatches.libs.retrooper.io.packetevents.injector.handlers.PacketEventsDecoder.decode(PacketEventsDecoder.java:41) ~[ServerPatches-Paper.jar:?]
	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:88) ~[netty-codec-4.1.97.Final.jar:4.1.97.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444) ~[netty-transport-4.1.97.Final.jar:4.1.97.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420) ~[netty-transport-4.1.97.Final.jar:4.1.97.Final]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412) ~[netty-transport-4.1.97.Final.jar:4.1.97.Final]
	at ProtocolLib (26).jar/com.comphenix.protocol.injector.netty.channel.InboundProtocolReader.channelRead(InboundProtocolReader.java:25) ~[ProtocolLib (26).jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444) ~[netty-transport-4.1.97.Final.jar:4.1.97.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420) ~[netty-transport-4.1.97.Final.jar:4.1.97.Final]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412) ~[netty-transport-4.1.97.Final.jar:4.1.97.Final]
	at io.netty.handler.flow.FlowControlHandler.dequeue(FlowControlHandler.java:202) ~[netty-handler-4.1.97.Final.jar:4.1.97.Final]
	at io.netty.handler.flow.FlowControlHandler.channelRead(FlowControlHandler.java:164) ~[netty-handler-4.1.97.Final.jar:4.1.97.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:442) ~[netty-transport-4.1.97.Final.jar:4.1.97.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420) ~[netty-transport-4.1.97.Final.jar:4.1.97.Final]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412) ~[netty-transport-4.1.97.Final.jar:4.1.97.Final]
	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103) ~[netty-codec-4.1.97.Final.jar:4.1.97.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444) ~[netty-transport-4.1.97.Final.jar:4.1.97.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420) ~[netty-transport-4.1.97.Final.jar:4.1.97.Final]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412) ~[netty-transport-4.1.97.Final.jar:4.1.97.Final]
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:346) ~[netty-codec-4.1.97.Final.jar:4.1.97.Final]
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:318) ~[netty-codec-4.1.97.Final.jar:4.1.97.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444) ~[netty-transport-4.1.97.Final.jar:4.1.97.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420) ~[netty-transport-4.1.97.Final.jar:4.1.97.Final]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412) ~[netty-transport-4.1.97.Final.jar:4.1.97.Final]
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:346) ~[netty-codec-4.1.97.Final.jar:4.1.97.Final]
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:318) ~[netty-codec-4.1.97.Final.jar:4.1.97.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444) ~[netty-transport-4.1.97.Final.jar:4.1.97.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420) ~[netty-transport-4.1.97.Final.jar:4.1.97.Final]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412) ~[netty-transport-4.1.97.Final.jar:4.1.97.Final]
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:346) ~[netty-codec-4.1.97.Final.jar:4.1.97.Final]
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:318) ~[netty-codec-4.1.97.Final.jar:4.1.97.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444) ~[netty-transport-4.1.97.Final.jar:4.1.97.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420) ~[netty-transport-4.1.97.Final.jar:4.1.97.Final]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412) ~[netty-transport-4.1.97.Final.jar:4.1.97.Final]
	at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:286) ~[netty-handler-4.1.97.Final.jar:4.1.97.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:442) ~[netty-transport-4.1.97.Final.jar:4.1.97.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420) ~[netty-transport-4.1.97.Final.jar:4.1.97.Final]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412) ~[netty-transport-4.1.97.Final.jar:4.1.97.Final]
	at io.netty.handler.flush.FlushConsolidationHandler.channelRead(FlushConsolidationHandler.java:152) ~[netty-handler-4.1.97.Final.jar:4.1.97.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:442) ~[netty-transport-4.1.97.Final.jar:4.1.97.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420) ~[netty-transport-4.1.97.Final.jar:4.1.97.Final]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412) ~[netty-transport-4.1.97.Final.jar:4.1.97.Final]
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410) ~[netty-transport-4.1.97.Final.jar:4.1.97.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:440) ~[netty-transport-4.1.97.Final.jar:4.1.97.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420) ~[netty-transport-4.1.97.Final.jar:4.1.97.Final]
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919) ~[netty-transport-4.1.97.Final.jar:4.1.97.Final]
	at io.netty.channel.epoll.AbstractEpollStreamChannel$EpollStreamUnsafe.epollInReady(AbstractEpollStreamChannel.java:800) ~[netty-transport-classes-epoll-4.1.97.Final.jar:4.1.97.Final]
	at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:509) ~[netty-transport-classes-epoll-4.1.97.Final.jar:4.1.97.Final]
	at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:407) ~[netty-transport-classes-epoll-4.1.97.Final.jar:4.1.97.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997) ~[netty-common-4.1.97.Final.jar:4.1.97.Final]
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[netty-common-4.1.97.Final.jar:4.1.97.Final]```

**Comment by naikyys** [comment]
Can I get please help?

**Comment by Vilkogaymer** [comment]
> Can I get please help?

Ano mam pre teba najlepsiu pomoc a to zrus P2W na svojom serveru a prestan okradat deti LOL

**Comment by Summiner** [comment]
What version of the plugin are you currently using? /ver ServerPatches

**Comment by naikyys** [comment]
Hello, its the latest you got here on github.

**Comment by Vilkogaymer** [comment]
> Hello, its the latest you got here on github.

Zruš P2W ty šašo

**Comment by naikyys** [comment]
Hey, could you please fix these warnings. @Summiner ?

**Comment by Summiner** [comment]
Resolved in latest release
